//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string TicketNumber { get; set; }
        public string TicketType { get; set; }
        public Nullable<System.DateTime> DateOfInitiation { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Team { get; set; }
        public string Attachment { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string InitFeedback { get; set; }
        public string AssignedBy { get; set; }
        public string TypeOfReport { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string CompleterAttachment { get; set; }
        public string InitComments { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    }
}
